language: scala
scala:
  - 2.11.7
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - boris.malensek@zalando.de
script: "sbt clean coverage +test"
after_success: "sbt coveralls"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3eb93f2a0c2931a59d0d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always